// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQI-Spp2juqHCGQME_kmGvJ5dqvuFJA4',
    appId: '1:281201677274:web:4e74a512386068f36fa6e3',
    messagingSenderId: '281201677274',
    projectId: 'chatapp-22691',
    authDomain: 'chatapp-22691.firebaseapp.com',
    storageBucket: 'chatapp-22691.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAroJd-1RaaV6h0q4CIlPLtKEnLPd36Qpw',
    appId: '1:281201677274:android:83c575ebfd9706016fa6e3',
    messagingSenderId: '281201677274',
    projectId: 'chatapp-22691',
    storageBucket: 'chatapp-22691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjwxIO0ru-fgBlxIewUm5ET9UEMRZGlzc',
    appId: '1:281201677274:ios:9b47e444d49f127a6fa6e3',
    messagingSenderId: '281201677274',
    projectId: 'chatapp-22691',
    storageBucket: 'chatapp-22691.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjwxIO0ru-fgBlxIewUm5ET9UEMRZGlzc',
    appId: '1:281201677274:ios:9b47e444d49f127a6fa6e3',
    messagingSenderId: '281201677274',
    projectId: 'chatapp-22691',
    storageBucket: 'chatapp-22691.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJQI-Spp2juqHCGQME_kmGvJ5dqvuFJA4',
    appId: '1:281201677274:web:efc2895b9eec42db6fa6e3',
    messagingSenderId: '281201677274',
    projectId: 'chatapp-22691',
    authDomain: 'chatapp-22691.firebaseapp.com',
    storageBucket: 'chatapp-22691.appspot.com',
  );
}
